name: my-first-workflow
#To have a trigger on every push on this repo on any branch
on:
  push:
    branches:
      - dev
      - main
      - 'feature-*'

  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.0
      - name: Setup Java
        uses: actions/setup-java@v5.3.0
        with:
          distribution: temurin
          java-version: '21'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install maven
          mvn install
      - name: Run Unit Tests
        run: spring-test -v
          
        
