name: my-first-workflow

on:
  push:
    branches:
      - dev
      - main
      - 'feature-*'

  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Tests + Coverage
        run: mvn clean verify

      - name: Verify report exists
        run: ls -R target/site || echo "No report generated"

      # Create a directory for exported reports
      - name: Create coverage output directory
        run: mkdir -p coverage-report

      # Copy JaCoCo report into that directory
      - name: Copy coverage report
        run: cp -r target/site/jacoco/. coverage-report/

      # Upload coverage report as artifact (IMPORTANT in CI)
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: coverage-report

  download-coverage-report:
    name: Download Coverage Report
    runs-on: ubuntu-latest

    steps:
      #Download the coverage report artifact in another job (if needed)
      - name: Download coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-coverage-report    