name: my-first-workflow
#To have a trigger on every push on this repo on any branch
on: push


jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running Single Command in Job1
        run: echo "Hi I am thandolwethu Mdishwa and this is my first github workflow"
      - name: Checking OS Release for Github Hosted Runner
        run: cat /etc/os-release
